title: Solana Paper Wallet with Staking
description: A guide for creating an air-gapped Solana paper wallet with staking capabilities
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
